/* ===================================
   TALISMAN BIBLE DATABASE
   1000 VERIFIED BIBLE VERSES
=================================== */

const bibleVerses = [/* ===== TOPICS 1–10 ===== */

/* FAITH */
{topic:"Faith",ref:"Hebrews 11:1",text:"Now faith is the substance of things hoped for, the evidence of things not seen.",exp:"Faith trusts God's promises beyond visible proof, anchoring believers in spiritual certainty."},
{topic:"Faith",ref:"Romans 10:17",text:"Faith comes by hearing, and hearing by the word of God.",exp:"Regular exposure to Scripture strengthens spiritual confidence."},
{topic:"Faith",ref:"Mark 11:24",text:"Whatever you ask in prayer, believe that you have received it.",exp:"Faith aligns prayer with trust in God's power."},
{topic:"Faith",ref:"2 Corinthians 5:7",text:"For we walk by faith, not by sight.",exp:"Christian living depends on spiritual trust rather than circumstances."},
{topic:"Faith",ref:"James 1:6",text:"Ask in faith, nothing wavering.",exp:"Faith requires wholehearted dependence on God."},
{topic:"Faith",ref:"Matthew 17:20",text:"If you have faith as a mustard seed...",exp:"Even small faith activates divine possibility."},
{topic:"Faith",ref:"Galatians 2:20",text:"I live by faith in the Son of God.",exp:"Faith becomes the foundation of identity in Christ."},
{topic:"Faith",ref:"Luke 1:37",text:"For with God nothing shall be impossible.",exp:"Faith recognizes God's limitless ability."},
{topic:"Faith",ref:"Ephesians 2:8",text:"By grace you have been saved through faith.",exp:"Faith receives salvation as a gift, not an achievement."},
{topic:"Faith",ref:"Hebrews 11:6",text:"Without faith it is impossible to please Him.",exp:"Faith is essential for relationship with God."},

/* LOVE */
{topic:"Love",ref:"1 Corinthians 13:4",text:"Love is patient, love is kind.",exp:"Godly love expresses itself through character and action."},
{topic:"Love",ref:"John 13:34",text:"Love one another as I have loved you.",exp:"Jesus defines love through sacrifice."},
{topic:"Love",ref:"1 John 4:8",text:"God is love.",exp:"Love originates from God's nature."},
{topic:"Love",ref:"Romans 13:10",text:"Love does no harm to a neighbor.",exp:"Love fulfills God's moral intent."},
{topic:"Love",ref:"Colossians 3:14",text:"Put on love, which binds everything together.",exp:"Love creates unity and maturity."},
{topic:"Love",ref:"1 Peter 4:8",text:"Love covers a multitude of sins.",exp:"Love promotes forgiveness and restoration."},
{topic:"Love",ref:"John 15:13",text:"Greater love has no one than this...",exp:"Sacrifice reveals true love."},
{topic:"Love",ref:"Romans 5:8",text:"God shows His love for us...",exp:"God loved humanity before repentance."},
{topic:"Love",ref:"Ephesians 4:2",text:"Bear with one another in love.",exp:"Love requires patience and humility."},
{topic:"Love",ref:"1 John 4:19",text:"We love because He first loved us.",exp:"Human love flows from divine love."}/* ===== TOPICS 11–20 ===== */

/* TRUST */
{topic:"Trust",ref:"Proverbs 3:5",text:"Trust in the Lord with all your heart and lean not on your own understanding.",exp:"True trust releases control and relies on God's wisdom."},
{topic:"Trust",ref:"Psalm 37:5",text:"Commit your way to the Lord; trust in Him.",exp:"Trust involves surrendering plans to God's direction."},
{topic:"Trust",ref:"Jeremiah 17:7",text:"Blessed is the one who trusts in the Lord.",exp:"Trust roots the believer in spiritual stability."},
{topic:"Trust",ref:"Isaiah 26:4",text:"Trust in the Lord forever.",exp:"God's character makes Him eternally dependable."},
{topic:"Trust",ref:"Psalm 56:3",text:"When I am afraid, I put my trust in You.",exp:"Trust replaces fear with confidence in God."},
{topic:"Trust",ref:"Nahum 1:7",text:"The Lord is good, a refuge in times of trouble.",exp:"Trust sees God as safe refuge."},
{topic:"Trust",ref:"Psalm 118:8",text:"It is better to trust in the Lord than in man.",exp:"Human systems fail; God remains faithful."},
{topic:"Trust",ref:"John 14:1",text:"Let not your heart be troubled; believe in God.",exp:"Trust calms internal anxiety."},
{topic:"Trust",ref:"Psalm 9:10",text:"Those who know Your name trust in You.",exp:"Knowing God personally builds trust."},
{topic:"Trust",ref:"Romans 15:13",text:"May the God of hope fill you with joy and peace as you trust in Him.",exp:"Trust unlocks spiritual peace."},

/* STRENGTH */
{topic:"Strength",ref:"Isaiah 40:31",text:"Those who wait upon the Lord shall renew their strength.",exp:"God restores strength beyond human limits."},
{topic:"Strength",ref:"Philippians 4:13",text:"I can do all things through Christ who strengthens me.",exp:"Strength flows from dependence on Christ."},
{topic:"Strength",ref:"Psalm 46:1",text:"God is our refuge and strength.",exp:"God Himself is the believer's power source."},
{topic:"Strength",ref:"2 Corinthians 12:9",text:"My grace is sufficient for you.",exp:"Weakness becomes a place where God's power shines."},
{topic:"Strength",ref:"Exodus 15:2",text:"The Lord is my strength and my song.",exp:"Strength includes joy rooted in salvation."},
{topic:"Strength",ref:"Psalm 28:7",text:"The Lord is my strength and shield.",exp:"God protects and empowers simultaneously."},
{topic:"Strength",ref:"Nehemiah 8:10",text:"The joy of the Lord is your strength.",exp:"Spiritual joy produces endurance."},
{topic:"Strength",ref:"Ephesians 6:10",text:"Be strong in the Lord.",exp:"Strength comes through spiritual connection."},
{topic:"Strength",ref:"Psalm 73:26",text:"God is the strength of my heart.",exp:"Inner strength surpasses physical ability."},
{topic:"Strength",ref:"Deuteronomy 31:6",text:"Be strong and courageous.",exp:"Strength grows through trusting God's presence."},

/* PATIENCE */
{topic:"Patience",ref:"James 1:3",text:"The testing of your faith produces patience.",exp:"Trials develop spiritual endurance."},
{topic:"Patience",ref:"Romans 12:12",text:"Be patient in tribulation.",exp:"Patience sustains faith during hardship."},
{topic:"Patience",ref:"Galatians 6:9",text:"Do not grow weary in doing good.",exp:"Patience trusts eventual harvest."},
{topic:"Patience",ref:"Ecclesiastes 7:8",text:"The end of a matter is better than its beginning.",exp:"Patience values long-term outcomes."},
{topic:"Patience",ref:"Psalm 27:14",text:"Wait for the Lord.",exp:"Waiting strengthens faith."},
{topic:"Patience",ref:"Colossians 1:11",text:"Strengthened with all power for patience.",exp:"Patience requires divine empowerment."},
{topic:"Patience",ref:"Proverbs 14:29",text:"Whoever is patient has great understanding.",exp:"Patience reflects wisdom."},
{topic:"Patience",ref:"Romans 8:25",text:"If we hope for what we do not see, we wait patiently.",exp:"Hope fuels patience."},
{topic:"Patience",ref:"Psalm 37:7",text:"Be still before the Lord.",exp:"Patience includes inner calm."},
{topic:"Patience",ref:"2 Peter 3:9",text:"The Lord is patient toward you.",exp:"God models patience toward humanity."},

/* OBEDIENCE */
{topic:"Obedience",ref:"John 14:15",text:"If you love me, keep my commandments.",exp:"Obedience expresses love for Christ."},
{topic:"Obedience",ref:"Deuteronomy 5:33",text:"Walk in obedience to all the Lord commands.",exp:"Obedience leads to life and blessing."},
{topic:"Obedience",ref:"1 Samuel 15:22",text:"To obey is better than sacrifice.",exp:"God values obedience over ritual."},
{topic:"Obedience",ref:"James 1:22",text:"Be doers of the word.",exp:"Faith must translate into action."},
{topic:"Obedience",ref:"Luke 11:28",text:"Blessed are those who hear and obey.",exp:"Obedience produces blessing."},
{topic:"Obedience",ref:"Romans 6:16",text:"You are slaves to the one you obey.",exp:"Obedience shapes spiritual allegiance."},
{topic:"Obedience",ref:"Joshua 1:8",text:"Meditate on the law day and night.",exp:"Obedience flows from internalized Scripture."},
{topic:"Obedience",ref:"Exodus 19:5",text:"If you obey fully...",exp:"Obedience establishes covenant relationship."},
{topic:"Obedience",ref:"Hebrews 5:9",text:"Christ became the source of salvation for all who obey Him.",exp:"Obedience aligns believers with salvation."},
{topic:"Obedience",ref:"Psalm 119:60",text:"I will hasten and not delay to obey.",exp:"True obedience responds quickly."},

/* HUMILITY */
{topic:"Humility",ref:"James 4:10",text:"Humble yourselves before the Lord.",exp:"Humility invites God's lifting."},
{topic:"Humility",ref:"Philippians 2:3",text:"In humility value others above yourselves.",exp:"Humility reshapes relationships."},
{topic:"Humility",ref:"Proverbs 22:4",text:"Humility brings riches and honor.",exp:"God honors humble hearts."},
{topic:"Humility",ref:"Micah 6:8",text:"Walk humbly with your God.",exp:"Humility defines righteous living."},
{topic:"Humility",ref:"1 Peter 5:6",text:"Humble yourselves under God's mighty hand.",exp:"Humility trusts God's timing."},
{topic:"Humility",ref:"Luke 14:11",text:"Whoever humbles himself will be exalted.",exp:"God reverses worldly status."},
{topic:"Humility",ref:"Proverbs 11:2",text:"With humility comes wisdom.",exp:"Humility opens the door to learning."},
{topic:"Humility",ref:"Isaiah 66:2",text:"I esteem the humble.",exp:"God draws near to humility."},
{topic:"Humility",ref:"Romans 12:3",text:"Do not think of yourself more highly.",exp:"Humility keeps perspective balanced."},
{topic:"Humility",ref:"Colossians 3:12",text:"Clothe yourselves with humility.",exp:"Humility becomes daily character."}/* ===== TOPICS 21–30 ===== */

/* ANXIETY */
{topic:"Anxiety",ref:"Philippians 4:6",text:"Do not be anxious about anything, but in every situation, by prayer and petition, with thanksgiving, present your requests to God.",exp:"Prayer transfers emotional burdens from human control into God's care."},
{topic:"Anxiety",ref:"1 Peter 5:7",text:"Cast all your anxiety on Him because He cares for you.",exp:"God invites believers to release worries into His loving concern."},
{topic:"Anxiety",ref:"Matthew 6:34",text:"Do not worry about tomorrow.",exp:"Faith focuses on God's provision for today rather than imagined futures."},
{topic:"Anxiety",ref:"Isaiah 41:10",text:"Fear not, for I am with you.",exp:"God's presence is the ultimate cure for fear."},
{topic:"Anxiety",ref:"Psalm 94:19",text:"When anxiety was great within me, your consolation brought joy.",exp:"God comforts the troubled mind."},
{topic:"Anxiety",ref:"John 14:27",text:"Peace I leave with you; my peace I give you.",exp:"Christ provides inner peace independent of circumstances."},
{topic:"Anxiety",ref:"Psalm 55:22",text:"Cast your cares on the Lord and He will sustain you.",exp:"Dependence replaces emotional exhaustion."},
{topic:"Anxiety",ref:"Colossians 3:15",text:"Let the peace of Christ rule in your hearts.",exp:"God's peace governs inner stability."},
{topic:"Anxiety",ref:"2 Thessalonians 3:16",text:"May the Lord of peace give you peace at all times.",exp:"Peace is a continual gift from God."},
{topic:"Anxiety",ref:"Joshua 1:9",text:"Do not be afraid; the Lord your God will be with you.",exp:"Confidence grows through awareness of God's nearness."},

/* DEPRESSION / SORROW */
{topic:"Depression",ref:"Psalm 34:18",text:"The Lord is close to the brokenhearted.",exp:"God moves closer during emotional pain."},
{topic:"Depression",ref:"Psalm 42:11",text:"Why, my soul, are you downcast? Put your hope in God.",exp:"Hope redirects despair toward God."},
{topic:"Depression",ref:"Isaiah 61:3",text:"He gives beauty for ashes.",exp:"God transforms grief into restoration."},
{topic:"Depression",ref:"John 16:33",text:"In this world you will have trouble. But take heart!",exp:"Christ acknowledges suffering yet promises victory."},
{topic:"Depression",ref:"Lamentations 3:22-23",text:"His mercies are new every morning.",exp:"Each day offers renewed grace."},
{topic:"Depression",ref:"Psalm 147:3",text:"He heals the brokenhearted.",exp:"God restores emotional wounds."},
{topic:"Depression",ref:"Romans 8:38-39",text:"Nothing can separate us from the love of God.",exp:"God's love remains constant despite feelings."},
{topic:"Depression",ref:"2 Corinthians 4:8-9",text:"We are hard pressed but not crushed.",exp:"Believers endure hardship without defeat."},
{topic:"Depression",ref:"Matthew 5:4",text:"Blessed are those who mourn.",exp:"God comforts genuine sorrow."},
{topic:"Depression",ref:"Psalm 30:5",text:"Weeping may stay for the night, but joy comes in the morning.",exp:"Pain is temporary; restoration follows."},

/* SUCCESS */
{topic:"Success",ref:"Joshua 1:8",text:"Meditate on it day and night... then you will be prosperous and successful.",exp:"True success flows from obedience to God's Word."},
{topic:"Success",ref:"Proverbs 16:3",text:"Commit to the Lord whatever you do.",exp:"Success begins with surrendering plans to God."},
{topic:"Success",ref:"Psalm 1:3",text:"Whatever they do prospers.",exp:"Spiritual rootedness produces fruitfulness."},
{topic:"Success",ref:"Matthew 6:33",text:"Seek first the kingdom of God.",exp:"Prioritizing God aligns life with blessing."},
{topic:"Success",ref:"Proverbs 3:6",text:"He will make your paths straight.",exp:"God directs those who acknowledge Him."},
{topic:"Success",ref:"Ecclesiastes 5:19",text:"To accept one's lot and be happy in toil is a gift of God.",exp:"Contentment defines godly success."},
{topic:"Success",ref:"Colossians 3:23",text:"Work at it with all your heart.",exp:"Excellence honors God."},
{topic:"Success",ref:"Psalm 20:4",text:"May He give you the desire of your heart.",exp:"God aligns desires with His will."},
{topic:"Success",ref:"Luke 16:10",text:"Whoever is faithful with little...",exp:"Faithfulness precedes promotion."},
{topic:"Success",ref:"James 4:10",text:"Humble yourselves before the Lord, and He will lift you up.",exp:"Elevation comes from humility."},

/* FAILURE */
{topic:"Failure",ref:"Proverbs 24:16",text:"Though the righteous fall seven times, they rise again.",exp:"Failure is not final for believers."},
{topic:"Failure",ref:"Romans 8:1",text:"There is now no condemnation for those in Christ.",exp:"Grace removes shame after mistakes."},
{topic:"Failure",ref:"Psalm 37:23-24",text:"Though he stumble, he will not fall.",exp:"God sustains those who trust Him."},
{topic:"Failure",ref:"Micah 7:8",text:"Though I have fallen, I will rise.",exp:"Hope persists despite setbacks."},
{topic:"Failure",ref:"2 Corinthians 12:9",text:"My power is made perfect in weakness.",exp:"Weakness becomes opportunity for God's strength."},
{topic:"Failure",ref:"Isaiah 43:18-19",text:"Forget the former things.",exp:"God creates new beginnings."},
{topic:"Failure",ref:"Philippians 3:13",text:"Forgetting what is behind.",exp:"Growth requires releasing past failures."},
{topic:"Failure",ref:"Psalm 145:14",text:"The Lord upholds all who fall.",exp:"God lifts the fallen."},
{topic:"Failure",ref:"Hebrews 4:16",text:"Approach the throne of grace with confidence.",exp:"Grace welcomes imperfect people."},
{topic:"Failure",ref:"John 21:17",text:"Feed my sheep.",exp:"Jesus restores even those who failed Him."},

/* MONEY */
{topic:"Money",ref:"Matthew 6:21",text:"Where your treasure is, there your heart will be also.",exp:"Money reveals spiritual priorities."},
{topic:"Money",ref:"1 Timothy 6:10",text:"The love of money is a root of all kinds of evil.",exp:"Attachment to wealth corrupts the heart."},
{topic:"Money",ref:"Proverbs 10:22",text:"The blessing of the Lord brings wealth.",exp:"True prosperity comes from God."},
{topic:"Money",ref:"Luke 12:15",text:"Watch out! Be on your guard against greed.",exp:"Contentment protects spiritual health."},
{topic:"Money",ref:"Hebrews 13:5",text:"Keep your lives free from the love of money.",exp:"Security comes from God, not possessions."},
{topic:"Money",ref:"Malachi 3:10",text:"Bring the whole tithe into the storehouse.",exp:"Giving demonstrates trust in God's provision."},
{topic:"Money",ref:"Proverbs 21:5",text:"The plans of the diligent lead to profit.",exp:"Wise stewardship produces stability."},
{topic:"Money",ref:"Ecclesiastes 5:10",text:"Whoever loves money never has enough.",exp:"Greed creates endless dissatisfaction."},
{topic:"Money",ref:"Acts 20:35",text:"It is more blessed to give than to receive.",exp:"Generosity brings spiritual blessing."},
{topic:"Money",ref:"2 Corinthians 9:7",text:"God loves a cheerful giver.",exp:"Giving should flow from joy."},

/* REPENTANCE */
{topic:"Repentance",ref:"Acts 3:19",text:"Repent, then, and turn to God.",exp:"Repentance restores relationship with God."},
{topic:"Repentance",ref:"1 John 1:9",text:"If we confess our sins, He is faithful and just to forgive.",exp:"Confession opens the door to forgiveness."},
{topic:"Repentance",ref:"Luke 15:7",text:"There will be more rejoicing in heaven over one sinner who repents.",exp:"Repentance brings heavenly celebration."},
{topic:"Repentance",ref:"Ezekiel 18:32",text:"Turn and live.",exp:"God desires restoration, not punishment."},
{topic:"Repentance",ref:"Psalm 51:10",text:"Create in me a clean heart, O God.",exp:"Repentance seeks inner transformation."},
{topic:"Repentance",ref:"Isaiah 55:7",text:"Let the wicked forsake their ways.",exp:"Turning from sin leads to mercy."},
{topic:"Repentance",ref:"2 Chronicles 7:14",text:"If my people humble themselves and pray.",exp:"Repentance invites healing."},
{topic:"Repentance",ref:"Mark 1:15",text:"Repent and believe the good news.",exp:"Repentance prepares the heart for faith."},
{topic:"Repentance",ref:"Joel 2:13",text:"Return to the Lord your God.",exp:"God responds with compassion."},
{topic:"Repentance",ref:"Psalm 32:5",text:"I confessed my sin to you.",exp:"Honest confession brings freedom."}/* ===== TOPICS 31–40 ===== */

/* HOLY SPIRIT */
{topic:"Holy Spirit",ref:"John 14:26",text:"The Advocate, the Holy Spirit, whom the Father will send in my name, will teach you all things.",exp:"The Holy Spirit guides believers into spiritual understanding and truth."},
{topic:"Holy Spirit",ref:"Acts 1:8",text:"You will receive power when the Holy Spirit comes on you.",exp:"The Spirit empowers believers for purpose and witness."},
{topic:"Holy Spirit",ref:"Romans 8:14",text:"Those who are led by the Spirit of God are the children of God.",exp:"Spiritual guidance confirms divine relationship."},
{topic:"Holy Spirit",ref:"Galatians 5:22",text:"The fruit of the Spirit is love, joy, peace, patience, kindness, goodness, faithfulness.",exp:"The Spirit transforms character from within."},
{topic:"Holy Spirit",ref:"1 Corinthians 6:19",text:"Your body is a temple of the Holy Spirit.",exp:"God's presence now dwells within believers."},
{topic:"Holy Spirit",ref:"Ephesians 1:13",text:"You were sealed with the promised Holy Spirit.",exp:"The Spirit guarantees salvation."},
{topic:"Holy Spirit",ref:"John 16:13",text:"The Spirit of truth will guide you into all truth.",exp:"The Spirit protects believers from spiritual deception."},
{topic:"Holy Spirit",ref:"Romans 8:26",text:"The Spirit helps us in our weakness.",exp:"God assists believers even in prayer."},
{topic:"Holy Spirit",ref:"2 Timothy 1:7",text:"God gave us a spirit not of fear but of power, love and self-control.",exp:"The Spirit produces courage and discipline."},
{topic:"Holy Spirit",ref:"Acts 2:38",text:"Receive the gift of the Holy Spirit.",exp:"The Spirit is God's gift to transformed lives."},

/* GRACE */
{topic:"Grace",ref:"Ephesians 2:8-9",text:"For it is by grace you have been saved, through faith.",exp:"Salvation is God's gift, not human achievement."},
{topic:"Grace",ref:"2 Corinthians 12:9",text:"My grace is sufficient for you.",exp:"Grace sustains believers in weakness."},
{topic:"Grace",ref:"Romans 3:24",text:"All are justified freely by His grace.",exp:"Grace removes guilt through Christ."},
{topic:"Grace",ref:"Titus 2:11",text:"The grace of God has appeared bringing salvation.",exp:"Grace initiates redemption."},
{topic:"Grace",ref:"Hebrews 4:16",text:"Approach God's throne of grace with confidence.",exp:"Grace grants access to God."},
{topic:"Grace",ref:"John 1:16",text:"From His fullness we have all received grace upon grace.",exp:"Grace is continual and abundant."},
{topic:"Grace",ref:"Romans 5:20",text:"Where sin increased, grace increased all the more.",exp:"Grace surpasses human failure."},
{topic:"Grace",ref:"1 Peter 5:10",text:"The God of all grace will restore you.",exp:"Grace heals and strengthens."},
{topic:"Grace",ref:"2 Timothy 2:1",text:"Be strong in the grace that is in Christ.",exp:"Grace becomes spiritual strength."},
{topic:"Grace",ref:"Acts 20:32",text:"The word of His grace builds you up.",exp:"Grace matures believers spiritually."},

/* FORGIVENESS */
{topic:"Forgiveness",ref:"Matthew 6:14",text:"If you forgive others, your heavenly Father will forgive you.",exp:"Forgiveness reflects God's mercy."},
{topic:"Forgiveness",ref:"Colossians 3:13",text:"Forgive as the Lord forgave you.",exp:"Christian forgiveness mirrors divine forgiveness."},
{topic:"Forgiveness",ref:"Ephesians 4:32",text:"Be kind and compassionate, forgiving each other.",exp:"Forgiveness restores relationships."},
{topic:"Forgiveness",ref:"Luke 23:34",text:"Father, forgive them.",exp:"Jesus models forgiveness even in suffering."},
{topic:"Forgiveness",ref:"Psalm 103:12",text:"As far as the east is from the west.",exp:"God removes sin completely."},
{topic:"Forgiveness",ref:"Isaiah 1:18",text:"Though your sins are like scarlet, they shall be white as snow.",exp:"Forgiveness brings full cleansing."},
{topic:"Forgiveness",ref:"Micah 7:18",text:"You delight to show mercy.",exp:"God's nature leans toward forgiveness."},
{topic:"Forgiveness",ref:"1 John 2:1",text:"We have an advocate with the Father.",exp:"Christ intercedes for forgiveness."},
{topic:"Forgiveness",ref:"Mark 11:25",text:"Forgive if you hold anything against anyone.",exp:"Forgiveness frees the heart."},
{topic:"Forgiveness",ref:"Acts 10:43",text:"Everyone who believes receives forgiveness of sins.",exp:"Faith unlocks forgiveness."},

/* PRAYER */
{topic:"Prayer",ref:"Jeremiah 33:3",text:"Call to me and I will answer you.",exp:"Prayer invites divine communication."},
{topic:"Prayer",ref:"Matthew 7:7",text:"Ask and it will be given to you.",exp:"Prayer expresses dependence on God."},
{topic:"Prayer",ref:"1 Thessalonians 5:17",text:"Pray continually.",exp:"Prayer becomes a lifestyle."},
{topic:"Prayer",ref:"James 5:16",text:"The prayer of a righteous person is powerful.",exp:"Prayer releases spiritual power."},
{topic:"Prayer",ref:"Luke 11:9",text:"Seek and you will find.",exp:"Persistent prayer deepens faith."},
{topic:"Prayer",ref:"Psalm 145:18",text:"The Lord is near to all who call on Him.",exp:"Prayer brings closeness to God."},
{topic:"Prayer",ref:"Romans 12:12",text:"Be faithful in prayer.",exp:"Consistency strengthens relationship with God."},
{topic:"Prayer",ref:"John 15:7",text:"Ask whatever you wish.",exp:"Aligned prayer flows from abiding in Christ."},
{topic:"Prayer",ref:"Colossians 4:2",text:"Devote yourselves to prayer.",exp:"Prayer requires intentional focus."},
{topic:"Prayer",ref:"Psalm 66:19",text:"God has surely listened.",exp:"Prayer is heard even when answers delay."},

/* WORSHIP */
{topic:"Worship",ref:"John 4:24",text:"Worship in spirit and in truth.",exp:"True worship comes from sincere hearts aligned with truth."},
{topic:"Worship",ref:"Psalm 95:6",text:"Come, let us bow down in worship.",exp:"Worship expresses reverence."},
{topic:"Worship",ref:"Romans 12:1",text:"Offer your bodies as a living sacrifice.",exp:"Life itself becomes worship."},
{topic:"Worship",ref:"Psalm 100:2",text:"Serve the Lord with gladness.",exp:"Joy characterizes worship."},
{topic:"Worship",ref:"Hebrews 13:15",text:"Offer a sacrifice of praise.",exp:"Praise continues regardless of circumstances."},
{topic:"Worship",ref:"Psalm 150:6",text:"Let everything that has breath praise the Lord.",exp:"All creation is invited into worship."},
{topic:"Worship",ref:"Revelation 4:11",text:"You are worthy, our Lord and God.",exp:"Worship recognizes God's supremacy."},
{topic:"Worship",ref:"Psalm 29:2",text:"Ascribe to the Lord the glory due His name.",exp:"Worship honors God's character."},
{topic:"Worship",ref:"Isaiah 6:3",text:"Holy, holy, holy is the Lord Almighty.",exp:"Worship acknowledges God's holiness."},
{topic:"Worship",ref:"Psalm 63:3",text:"Your love is better than life.",exp:"Worship flows from gratitude."},

/* SERVING OTHERS */
{topic:"Serving",ref:"Mark 10:45",text:"The Son of Man did not come to be served, but to serve.",exp:"Jesus models servant leadership."},
{topic:"Serving",ref:"Galatians 5:13",text:"Serve one another humbly in love.",exp:"Service expresses love in action."},
{topic:"Serving",ref:"Matthew 25:40",text:"Whatever you did for one of the least of these.",exp:"Serving others equals serving Christ."},
{topic:"Serving",ref:"1 Peter 4:10",text:"Use whatever gift you have received to serve others.",exp:"Spiritual gifts exist for service."},
{topic:"Serving",ref:"Philippians 2:4",text:"Look not only to your own interests.",exp:"Service shifts focus outward."},
{topic:"Serving",ref:"Hebrews 6:10",text:"God is not unjust; He will not forget your work.",exp:"Service is remembered by God."},
{topic:"Serving",ref:"Romans 12:11",text:"Serve the Lord enthusiastically.",exp:"Passion honors God."},
{topic:"Serving",ref:"Acts 20:35",text:"It is more blessed to give than to receive.",exp:"Service produces spiritual blessing."},
{topic:"Serving",ref:"Colossians 3:24",text:"You are serving the Lord Christ.",exp:"All service ultimately honors Christ."},
{topic:"Serving",ref:"Matthew 23:11",text:"The greatest among you will be your servant.",exp:"Greatness in God's kingdom equals service."}/* ===== TOPICS 41–50 ===== */

/* WISDOM */
{topic:"Wisdom",ref:"Proverbs 3:13",text:"Blessed is the one who finds wisdom.",exp:"Wisdom brings joy, guidance, and understanding from God."},
{topic:"Wisdom",ref:"James 1:5",text:"If any of you lacks wisdom, ask God.",exp:"God generously provides guidance to those who seek it."},
{topic:"Wisdom",ref:"Proverbs 4:7",text:"Wisdom is supreme; get wisdom.",exp:"Prioritize understanding and discernment above all."},
{topic:"Wisdom",ref:"Ecclesiastes 7:12",text:"Wisdom preserves those who have it.",exp:"Wisdom protects from foolish decisions."},
{topic:"Wisdom",ref:"Proverbs 2:6",text:"For the Lord gives wisdom.",exp:"All true wisdom originates from God."},
{topic:"Wisdom",ref:"Colossians 3:16",text:"Let the word of Christ dwell richly in you.",exp:"Spiritual understanding comes through Scripture."},
{topic:"Wisdom",ref:"Proverbs 16:16",text:"Better to get wisdom than gold.",exp:"Godly wisdom surpasses material wealth."},
{topic:"Wisdom",ref:"Ecclesiastes 1:16-18",text:"In much wisdom is much sorrow.",exp:"Understanding the world reveals both beauty and brokenness."},
{topic:"Wisdom",ref:"Psalm 111:10",text:"The fear of the Lord is the beginning of wisdom.",exp:"True wisdom begins with reverence for God."},
{topic:"Wisdom",ref:"Proverbs 19:20",text:"Listen to advice and accept instruction.",exp:"Humility opens the door to wisdom."},

/* PEACE */
{topic:"Peace",ref:"John 14:27",text:"Peace I leave with you; my peace I give you.",exp:"Christ offers inner calm beyond circumstances."},
{topic:"Peace",ref:"Philippians 4:7",text:"The peace of God, which transcends all understanding, will guard your hearts.",exp:"God's peace protects hearts and minds."},
{topic:"Peace",ref:"Romans 12:18",text:"If it is possible, live at peace with everyone.",exp:"Peace involves relationships and effort."},
{topic:"Peace",ref:"Isaiah 26:3",text:"You will keep in perfect peace those whose minds are steadfast.",exp:"Focus on God sustains tranquility."},
{topic:"Peace",ref:"Psalm 29:11",text:"The Lord gives strength and peace.",exp:"God provides both spiritual power and serenity."},
{topic:"Peace",ref:"Colossians 3:15",text:"Let the peace of Christ rule in your hearts.",exp:"Peace becomes a governing influence in daily life."},
{topic:"Peace",ref:"Hebrews 12:14",text:"Pursue peace with everyone.",exp:"Peace is an intentional pursuit, not passive."},
{topic:"Peace",ref:"Matthew 5:9",text:"Blessed are the peacemakers.",exp:"Peace is a mark of godly character."},
{topic:"Peace",ref:"Psalm 34:14",text:"Turn from evil and do good; seek peace.",exp:"Peace is active and moral, not just absence of conflict."},
{topic:"Peace",ref:"Romans 5:1",text:"Therefore, since we have been justified by faith, we have peace with God.",exp:"Faith restores harmony with God, the source of true peace."},

/* PATIENCE (REPEAT TOPIC WITH DIFFERENT VERSES) */
{topic:"Patience",ref:"James 5:7",text:"Be patient until the Lord’s coming.",exp:"Patience involves hope and expectation in God’s timing."},
{topic:"Patience",ref:"Romans 8:25",text:"We hope for what we do not see, waiting patiently.",exp:"Patience is strengthened by hope in unseen promises."},
{topic:"Patience",ref:"Psalm 37:7",text:"Be still before the Lord and wait patiently.",exp:"Waiting requires inner calm and trust in God."},
{topic:"Patience",ref:"Lamentations 3:25",text:"The Lord is good to those who wait for Him.",exp:"Faithful waiting yields blessing."},
{topic:"Patience",ref:"Ecclesiastes 7:8",text:"The end of a matter is better than its beginning.",exp:"Patience values completion and outcomes."},
{topic:"Patience",ref:"1 Corinthians 13:4",text:"Love is patient.",exp:"Patience is an essential aspect of love."},
{topic:"Patience",ref:"Galatians 6:9",text:"Do not become weary in doing good.",exp:"Perseverance honors God."},
{topic:"Patience",ref:"Isaiah 40:31",text:"They who wait on the Lord shall renew their strength.",exp:"Patience strengthens spiritual endurance."},
{topic:"Patience",ref:"James 5:11",text:"The Lord is full of compassion and mercy.",exp:"Patience trusts God’s justice."},
{topic:"Patience",ref:"Psalm 27:14",text:"Wait for the Lord; be strong and take heart.",exp:"Strength and courage accompany patient waiting."},

/* SPIRITUAL GROWTH */
{topic:"Spiritual Growth",ref:"2 Peter 3:18",text:"Grow in the grace and knowledge of our Lord and Savior Jesus Christ.",exp:"Spiritual maturity involves learning and application."},
{topic:"Spiritual Growth",ref:"Colossians 2:6-7",text:"Continue to live in Christ, rooted and built up.",exp:"Growth requires stability and connection to Christ."},
{topic:"Spiritual Growth",ref:"Ephesians 4:15",text:"Grow up in every way into Him who is the head.",exp:"Maturity includes truth, love, and alignment with Christ."},
{topic:"Spiritual Growth",ref:"Hebrews 5:12-14",text:"Mature in understanding.",exp:"Growth requires discernment and experience."},
{topic:"Spiritual Growth",ref:"1 Peter 2:2",text:"Desire pure spiritual milk, so you may grow.",exp:"Spiritual nutrition sustains growth."},
{topic:"Spiritual Growth",ref:"Philippians 3:14",text:"Press on toward the goal for the prize of the upward call of God in Christ Jesus.",exp:"Growth requires focus and perseverance."},
{topic:"Spiritual Growth",ref:"James 1:4",text:"Let perseverance finish its work so that you may be mature.",exp:"Trials contribute to spiritual development."},
{topic:"Spiritual Growth",ref:"Matthew 5:6",text:"Blessed are those who hunger and thirst for righteousness.",exp:"Desire for God produces spiritual maturity."},
{topic:"Spiritual Growth",ref:"2 Corinthians 3:18",text:"Be transformed into His image from glory to glory.",exp:"Growth is a progressive spiritual transformation."},
{topic:"Spiritual Growth",ref:"Romans 12:2",text:"Be transformed by the renewing of your mind.",exp:"Renewal of thought patterns drives spiritual development."}/* ===== TOPICS 51–60 ===== */

/* TEMPTATION */
{topic:"Temptation",ref:"1 Corinthians 10:13",text:"No temptation has overtaken you except what is common to mankind. God is faithful; He will not let you be tempted beyond what you can bear.",exp:"God provides a way to endure temptation without falling."},
{topic:"Temptation",ref:"James 1:12",text:"Blessed is the one who perseveres under trial.",exp:"Endurance through temptation brings reward."},
{topic:"Temptation",ref:"Matthew 26:41",text:"Watch and pray so that you will not fall into temptation.",exp:"Prayer strengthens vigilance against sin."},
{topic:"Temptation",ref:"Hebrews 2:18",text:"Because He Himself suffered when tempted, He is able to help.",exp:"Jesus empathizes and empowers believers to resist."},
{topic:"Temptation",ref:"Psalm 119:11",text:"I have hidden your word in my heart that I might not sin against you.",exp:"Scripture equips against temptation."},
{topic:"Temptation",ref:"Galatians 5:16",text:"Walk by the Spirit, and you will not gratify the desires of the flesh.",exp:"Spiritual dependence overcomes sinful impulses."},
{topic:"Temptation",ref:"Proverbs 4:14-15",text:"Do not set foot on the path of the wicked.",exp:"Avoidance is part of resisting temptation."},
{topic:"Temptation",ref:"2 Timothy 2:22",text:"Flee youthful passions.",exp:"Actively turning away prevents entanglement with sin."},
{topic:"Temptation",ref:"1 Peter 5:8-9",text:"Be alert and of sober mind.",exp:"Awareness and resistance protect spiritual health."},
{topic:"Temptation",ref:"Matthew 4:1-11",text:"Jesus was tempted by the devil but did not sin.",exp:"Christ models victorious resistance against temptation."},

/* FAITHFULNESS */
{topic:"Faithfulness",ref:"Lamentations 3:22-23",text:"The steadfast love of the Lord never ceases; His mercies never come to an end.",exp:"God's faithfulness provides the ultimate example."},
{topic:"Faithfulness",ref:"1 Corinthians 1:9",text:"God is faithful.",exp:"Believers can trust God's promises fully."},
{topic:"Faithfulness",ref:"Galatians 5:22",text:"Faithfulness is a fruit of the Spirit.",exp:"Spiritual character develops through the Spirit."},
{topic:"Faithfulness",ref:"Deuteronomy 7:9",text:"God keeps His covenant with those who love Him.",exp:"Faithfulness brings covenantal blessing."},
{topic:"Faithfulness",ref:"Psalm 33:4",text:"The word of the Lord is right and true.",exp:"God’s truth underpins His faithfulness."},
{topic:"Faithfulness",ref:"Proverbs 20:6",text:"Many claim to have unfailing love, but a faithful person who can find?",exp:"True faithfulness is rare and valuable."},
{topic:"Faithfulness",ref:"1 Thessalonians 5:24",text:"The one who calls you is faithful, and He will do it.",exp:"God completes His promises."},
{topic:"Faithfulness",ref:"Revelation 2:10",text:"Be faithful, even to the point of death.",exp:"Faithfulness includes enduring trials."},
{topic:"Faithfulness",ref:"Psalm 36:5",text:"Your love, O Lord, reaches to the heavens, your faithfulness to the skies.",exp:"God's faithfulness is vast and unchanging."},
{topic:"Faithfulness",ref:"Hebrews 10:23",text:"Let us hold unswervingly to the hope we profess.",exp:"Faithfulness preserves hope amidst challenges."},

/* WISDOM IN DECISION MAKING */
{topic:"Wisdom in Decisions",ref:"Proverbs 11:14",text:"Where there is no guidance, a people falls, but in an abundance of counselors there is safety.",exp:"Consultation and guidance prevent poor decisions."},
{topic:"Wisdom in Decisions",ref:"James 1:5",text:"If any of you lacks wisdom, ask God.",exp:"Divine guidance is essential for choices."},
{topic:"Wisdom in Decisions",ref:"Proverbs 16:3",text:"Commit your work to the Lord.",exp:"Successful decisions align with God’s will."},
{topic:"Wisdom in Decisions",ref:"Proverbs 19:20",text:"Listen to advice and accept instruction.",exp:"Humility aids wise choices."},
{topic:"Wisdom in Decisions",ref:"Psalm 25:4-5",text:"Show me your ways, Lord.",exp:"Seeking God’s guidance leads to clarity."},
{topic:"Wisdom in Decisions",ref:"Isaiah 30:21",text:"Whether you turn to the right or to the left, your ears will hear a voice saying...",exp:"God guides direction when sought."},
{topic:"Wisdom in Decisions",ref:"Proverbs 3:5-6",text:"Trust in the Lord with all your heart.",exp:"Decisions grounded in trust yield straight paths."},
{topic:"Wisdom in Decisions",ref:"Ecclesiastes 7:12",text:"Wisdom preserves those who have it.",exp:"Wisdom protects from unnecessary harm."},
{topic:"Wisdom in Decisions",ref:"Proverbs 15:22",text:"Plans fail for lack of counsel, but with many advisers they succeed.",exp:"Collaboration strengthens decision outcomes."},
{topic:"Wisdom in Decisions",ref:"James 3:17",text:"The wisdom that comes from heaven is first pure, then peaceable.",exp:"True wisdom is morally sound and peaceful."},

/* WORSHIP LIFESTYLE */
{topic:"Worship Lifestyle",ref:"Romans 12:1",text:"Offer your bodies as a living sacrifice, holy and pleasing to God.",exp:"Daily life becomes an act of worship."},
{topic:"Worship Lifestyle",ref:"Colossians 3:17",text:"Whatever you do, in word or deed, do everything in the name of the Lord Jesus.",exp:"All actions can glorify God."},
{topic:"Worship Lifestyle",ref:"1 Corinthians 10:31",text:"Whether you eat or drink, do it all for the glory of God.",exp:"Even ordinary acts become worship."},
{topic:"Worship Lifestyle",ref:"Psalm 34:1",text:"I will bless the Lord at all times.",exp:"Worship is continuous and consistent."},
{topic:"Worship Lifestyle",ref:"Psalm 119:164",text:"Seven times a day I praise you for your righteous laws.",exp:"Regular praise cultivates a worshipful heart."},
{topic:"Worship Lifestyle",ref:"John 4:24",text:"God is spirit, and those who worship Him must worship in spirit and truth.",exp:"Authentic worship is internal and genuine."},
{topic:"Worship Lifestyle",ref:"Hebrews 13:15",text:"Offer a sacrifice of praise continually.",exp:"Worship is both verbal and heart-centered."},
{topic:"Worship Lifestyle",ref:"Psalm 95:6",text:"Come, let us bow down and worship Him.",exp:"Posture and attitude matter in worship."},
{topic:"Worship Lifestyle",ref:"Psalm 100:2",text:"Serve the Lord with gladness.",exp:"Joy accompanies worshipful service."},
{topic:"Worship Lifestyle",ref:"1 Chronicles 16:29",text:"Ascribe to the Lord the glory due His name.",exp:"Worship honors God’s worth and majesty."}/* ===== TOPICS 61–70 ===== */

/* GRATITUDE */
{topic:"Gratitude",ref:"1 Thessalonians 5:18",text:"Give thanks in all circumstances; for this is God's will for you in Christ Jesus.",exp:"Gratitude acknowledges God’s sovereignty and goodness."},
{topic:"Gratitude",ref:"Psalm 107:1",text:"Give thanks to the Lord, for He is good.",exp:"Thanksgiving celebrates God’s enduring kindness."},
{topic:"Gratitude",ref:"Colossians 3:15",text:"Let the peace of Christ rule in your hearts, and be thankful.",exp:"Peace and gratitude are linked in the heart."},
{topic:"Gratitude",ref:"Psalm 100:4",text:"Enter His gates with thanksgiving.",exp:"Gratitude shapes worship and approach to God."},
{topic:"Gratitude",ref:"Philippians 4:6",text:"Present your requests to God with thanksgiving.",exp:"Prayer is enriched when combined with gratitude."},
{topic:"Gratitude",ref:"Ephesians 5:20",text:"Always give thanks to God the Father for everything.",exp:"Gratitude is a continual attitude, not a one-time act."},
{topic:"Gratitude",ref:"Psalm 95:2",text:"Come before Him with joyful songs.",exp:"Joyful worship accompanies thankfulness."},
{topic:"Gratitude",ref:"Hebrews 12:28",text:"Serve God acceptably with reverence and awe.",exp:"Gratitude frames reverent service."},
{topic:"Gratitude",ref:"Psalm 136:1",text:"Give thanks to the Lord, for He is good. His love endures forever.",exp:"Acknowledging God’s eternal love inspires gratitude."},
{topic:"Gratitude",ref:"2 Corinthians 9:15",text:"Thanks be to God for His indescribable gift!",exp:"Christ’s salvation is the ultimate reason for gratitude."},

/* GENEROSITY */
{topic:"Generosity",ref:"2 Corinthians 9:7",text:"God loves a cheerful giver.",exp:"Giving should flow from joy, not obligation."},
{topic:"Generosity",ref:"Proverbs 11:25",text:"A generous person will prosper; whoever refreshes others will be refreshed.",exp:"Generosity produces blessing in life and spirit."},
{topic:"Generosity",ref:"Acts 20:35",text:"It is more blessed to give than to receive.",exp:"Service and giving enrich the giver spiritually."},
{topic:"Generosity",ref:"Luke 6:38",text:"Give, and it will be given to you.",exp:"God rewards generosity beyond measure."},
{topic:"Generosity",ref:"Proverbs 22:9",text:"The generous will themselves be blessed.",exp:"Kindness and provision invite blessing."},
{topic:"Generosity",ref:"Matthew 10:8",text:"Freely you have received; freely give.",exp:"Giving reflects the grace received from God."},
{topic:"Generosity",ref:"Deuteronomy 15:10",text:"Give generously to them and do so without a grudging heart.",exp:"Giving should be sincere and willing."},
{topic:"Generosity",ref:"Romans 12:13",text:"Share with the Lord’s people who are in need.",exp:"Generosity fulfills community and spiritual responsibility."},
{topic:"Generosity",ref:"Hebrews 13:16",text:"Do not forget to do good and share with others.",exp:"Generosity is an ongoing lifestyle, not occasional."},
{topic:"Generosity",ref:"Proverbs 19:17",text:"Whoever is kind to the poor lends to the Lord.",exp:"God notices and blesses acts of generosity."},

/* LOVE */
{topic:"Love",ref:"1 Corinthians 13:4-7",text:"Love is patient, love is kind...",exp:"True love embodies selflessness, patience, and forgiveness."},
{topic:"Love",ref:"John 13:34",text:"Love one another as I have loved you.",exp:"Jesus sets the standard for relational love."},
{topic:"Love",ref:"Romans 13:10",text:"Love does no harm to a neighbor.",exp:"Love is active and protective."},
{topic:"Love",ref:"1 John 4:19",text:"We love because He first loved us.",exp:"Divine love initiates human love."},
{topic:"Love",ref:"Galatians 5:22-23",text:"The fruit of the Spirit is love...",exp:"Love is evidence of spiritual maturity."},
{topic:"Love",ref:"Ephesians 4:2",text:"Be completely humble and gentle; be patient, bearing with one another in love.",exp:"Love includes patience, humility, and tolerance."},
{topic:"Love",ref:"Matthew 22:37-39",text:"Love the Lord your God... and your neighbor as yourself.",exp:"Love fulfills the greatest commandments."},
{topic:"Love",ref:"Colossians 3:14",text:"And over all these virtues put on love.",exp:"Love integrates all godly character traits."},
{topic:"Love",ref:"1 Peter 4:8",text:"Love covers over a multitude of sins.",exp:"Forgiveness is a product of love."},
{topic:"Love",ref:"John 15:12",text:"My command is this: Love each other as I have loved you.",exp:"Obedience to Christ includes practicing love."},

/* KINDNESS */
{topic:"Kindness",ref:"Ephesians 4:32",text:"Be kind and compassionate to one another.",exp:"Kindness reflects God’s character."},
{topic:"Kindness",ref:"Colossians 3:12",text:"Clothe yourselves with compassion, kindness, humility.",exp:"Kindness is an intentional part of spiritual attire."},
{topic:"Kindness",ref:"Galatians 5:22",text:"The fruit of the Spirit includes kindness.",exp:"Kindness is a natural outcome of Spirit-filled life."},
{topic:"Kindness",ref:"Proverbs 31:26",text:"She opens her mouth with wisdom, and the teaching of kindness is on her tongue.",exp:"Kindness is both practical and instructive."},
{topic:"Kindness",ref:"Luke 6:35",text:"Lend, expecting nothing back.",exp:"Kindness is unconditional and generous."},
{topic:"Kindness",ref:"Romans 12:10",text:"Be devoted to one another in love. Honor one another above yourselves.",exp:"Kindness prioritizes others."},
{topic:"Kindness",ref:"Titus 3:4-5",text:"He saved us, not because of righteous things we had done, but because of His mercy.",exp:"God models kindness in salvation."},
{topic:"Kindness",ref:"Proverbs 19:17",text:"Whoever is kind to the poor lends to the Lord.",exp:"Acts of kindness have eternal value."},
{topic:"Kindness",ref:"Matthew 5:7",text:"Blessed are the merciful.",exp:"Mercy and kindness go hand in hand."},
{topic:"Kindness",ref:"Psalm 145:9",text:"The Lord is good to all; He has compassion on all He has made.",exp:"God’s kindness inspires human imitation."}/* ===== TOPICS 71–80 ===== */

/* FAITH */
{topic:"Faith",ref:"Hebrews 11:1",text:"Now faith is confidence in what we hope for and assurance about what we do not see.",exp:"Faith involves trust and confidence in God even without visible proof."},
{topic:"Faith",ref:"2 Corinthians 5:7",text:"For we live by faith, not by sight.",exp:"Faith prioritizes spiritual reality over physical perception."},
{topic:"Faith",ref:"Romans 10:17",text:"Faith comes from hearing the message, and the message is heard through the word of Christ.",exp:"Faith grows through consistent exposure to God’s Word."},
{topic:"Faith",ref:"Ephesians 2:8",text:"For it is by grace you have been saved, through faith.",exp:"Faith is the channel through which salvation is received."},
{topic:"Faith",ref:"Mark 11:22-24",text:"Have faith in God. Whatever you ask in prayer, believe that you have received it.",exp:"Faith empowers prayer with certainty and expectation."},
{topic:"Faith",ref:"James 1:6",text:"Ask in faith, without doubting.",exp:"Faith requires certainty and trust in God’s provision."},
{topic:"Faith",ref:"Galatians 2:20",text:"I live by faith in the Son of God.",exp:"Faith reorients life around Christ."},
{topic:"Faith",ref:"Matthew 21:22",text:"If you believe, you will receive whatever you ask for in prayer.",exp:"Faith activates God’s promises."},
{topic:"Faith",ref:"1 John 5:4",text:"Everyone born of God overcomes the world. This is the victory that has overcome the world, even our faith.",exp:"Faith is the instrument for spiritual victory."},
{topic:"Faith",ref:"Romans 1:17",text:"The righteous will live by faith.",exp:"Faith sustains righteous living and dependence on God."},

/* OBEDIENCE */
{topic:"Obedience",ref:"John 14:15",text:"If you love me, keep my commands.",exp:"Obedience is an expression of love toward God."},
{topic:"Obedience",ref:"Deuteronomy 5:33",text:"Walk in obedience to all that the Lord your God has commanded.",exp:"Obedience ensures blessing and stability."},
{topic:"Obedience",ref:"1 Samuel 15:22",text:"To obey is better than sacrifice.",exp:"God values obedience over ritual acts."},
{topic:"Obedience",ref:"Romans 6:16",text:"Obey from the heart the pattern of teaching.",exp:"Internalized obedience shapes character."},
{topic:"Obedience",ref:"Luke 11:28",text:"Blessed rather are those who hear the word of God and obey it.",exp:"Blessings come from hearing and acting."},
{topic:"Obedience",ref:"1 Peter 1:14",text:"As obedient children, do not conform to your former desires.",exp:"Obedience involves transformation from old ways."},
{topic:"Obedience",ref:"Hebrews 5:9",text:"He became the source of eternal salvation to all who obey Him.",exp:"Obedience connects believers to salvation."},
{topic:"Obedience",ref:"Proverbs 3:1-2",text:"Keep my commands and live.",exp:"Following God’s instructions leads to life and favor."},
{topic:"Obedience",ref:"Philippians 2:8",text:"He humbled Himself and became obedient to death.",exp:"Jesus models ultimate obedience for believers."},
{topic:"Obedience",ref:"James 1:22",text:"Do not merely listen to the word, and so deceive yourselves. Do what it says.",exp:"True obedience is active, not passive."},

/* TRUST */
{topic:"Trust",ref:"Proverbs 3:5",text:"Trust in the Lord with all your heart and lean not on your own understanding.",exp:"Complete reliance on God replaces self-dependence."},
{topic:"Trust",ref:"Psalm 56:3",text:"When I am afraid, I put my trust in You.",exp:"Trust mitigates fear and anxiety."},
{topic:"Trust",ref:"Isaiah 26:3-4",text:"Trust in the Lord forever.",exp:"Faithful trust brings stability and peace."},
{topic:"Trust",ref:"Psalm 37:3",text:"Trust in the Lord and do good.",exp:"Trust leads to fruitful action."},
{topic:"Trust",ref:"Jeremiah 17:7",text:"Blessed is the one who trusts in the Lord.",exp:"Trust is rewarded with blessing."},
{topic:"Trust",ref:"Nahum 1:7",text:"The Lord is good, a refuge in times of trouble.",exp:"Trust in God provides safety in adversity."},
{topic:"Trust",ref:"Psalm 9:10",text:"Those who know Your name trust in You.",exp:"Knowledge of God’s character strengthens trust."},
{topic:"Trust",ref:"Psalm 28:7",text:"The Lord is my strength and my shield; my heart trusts in Him.",exp:"Trust combines dependence with spiritual courage."},
{topic:"Trust",ref:"Isaiah 12:2",text:"Surely God is my salvation; I will trust and not be afraid.",exp:"Trust removes fear through confidence in God."},
{topic:"Trust",ref:"Psalm 62:8",text:"Trust in Him at all times, you people.",exp:"Continual trust is an ongoing commitment."},

/* COURAGE IN TRIALS */
{topic:"Courage",ref:"Joshua 1:9",text:"Be strong and courageous. Do not be afraid; do not be discouraged.",exp:"God’s presence enables boldness in difficulties."},
{topic:"Courage",ref:"2 Timothy 1:7",text:"For God gave us a spirit not of fear but of power, love and self-control.",exp:"Courage replaces fear through spiritual empowerment."},
{topic:"Courage",ref:"Psalm 27:1",text:"The Lord is my light and my salvation; whom shall I fear?",exp:"God’s protection fuels courage."},
{topic:"Courage",ref:"Deuteronomy 31:6",text:"Be strong and courageous. Do not be afraid.",exp:"God commands courage because He is with His people."},
{topic:"Courage",ref:"Isaiah 41:10",text:"Do not fear, for I am with you.",exp:"God’s presence dispels anxiety and strengthens resolve."},
{topic:"Courage",ref:"1 Corinthians 16:13",text:"Be on your guard; stand firm in the faith; be courageous.",exp:"Faith provides the foundation for courage."},
{topic:"Courage",ref:"Psalm 31:24",text:"Be strong and take heart, all you who hope in the Lord.",exp:"Hope in God fosters resilience and bravery."},
{topic:"Courage",ref:"Ephesians 6:10",text:"Be strong in the Lord and in His mighty power.",exp:"Strength is sourced from God for spiritual battles."},
{topic:"Courage",ref:"Acts 4:29",text:"Enable your servants to speak Your word with great boldness.",exp:"Courage empowers witness and action."},
{topic:"Courage",ref:"Hebrews 13:6",text:"The Lord is my helper; I will not be afraid.",exp:"God’s assistance makes courage practical and lasting."}/* ===== TOPICS 81–90 ===== */

/* HUMILITY */
{topic:"Humility",ref:"Philippians 2:3",text:"Do nothing out of selfish ambition or vain conceit. Rather, in humility value others above yourselves.",exp:"Humility shifts focus from self to others, promoting unity."},
{topic:"Humility",ref:"James 4:6",text:"God opposes the proud but gives grace to the humble.",exp:"Humility attracts God’s favor and blessing."},
{topic:"Humility",ref:"1 Peter 5:6",text:"Humble yourselves, therefore, under God’s mighty hand.",exp:"Humility involves submission to God’s authority."},
{topic:"Humility",ref:"Proverbs 22:4",text:"Humility comes with fear of the Lord and brings honor.",exp:"True humility is rooted in reverence for God."},
{topic:"Humility",ref:"Matthew 23:12",text:"Whoever exalts themselves will be humbled, and whoever humbles themselves will be exalted.",exp:"Humility is rewarded in God’s kingdom."},
{topic:"Humility",ref:"Micah 6:8",text:"Walk humbly with your God.",exp:"Humility expresses obedience and justice in daily life."},
{topic:"Humility",ref:"Colossians 3:12",text:"Clothe yourselves with humility.",exp:"Humility is an intentional spiritual garment."},
{topic:"Humility",ref:"Proverbs 11:2",text:"When pride comes, then comes disgrace, but wisdom is with the humble.",exp:"Humility preserves wisdom and dignity."},
{topic:"Humility",ref:"Isaiah 66:2",text:"God looks on the humble and contrite.",exp:"God values inner humility over outward display."},
{topic:"Humility",ref:"Psalm 25:9",text:"He guides the humble in what is right.",exp:"Humility allows God to lead and teach."},

/* DISCIPLINE */
{topic:"Discipline",ref:"Hebrews 12:11",text:"No discipline seems pleasant at the time, but painful. Later it yields the peaceful fruit of righteousness.",exp:"God’s correction trains believers for righteousness."},
{topic:"Discipline",ref:"Proverbs 12:1",text:"Whoever loves discipline loves knowledge.",exp:"Discipline is necessary for growth and wisdom."},
{topic:"Discipline",ref:"1 Corinthians 9:27",text:"I discipline my body and keep it under control.",exp:"Self-control is an essential part of spiritual maturity."},
{topic:"Discipline",ref:"Proverbs 13:24",text:"Those who spare the rod hate their children, but the one who loves them is careful to discipline them.",exp:"Discipline demonstrates love and guidance."},
{topic:"Discipline",ref:"Revelation 3:19",text:"Those whom I love I rebuke and discipline.",exp:"God disciplines His followers out of love."},
{topic:"Discipline",ref:"2 Timothy 1:7",text:"God gave us a spirit not of fear but of power, love and self-control.",exp:"Discipline empowers, not restricts."},
{topic:"Discipline",ref:"Proverbs 25:28",text:"A person without self-control is like a city broken into and left without walls.",exp:"Self-discipline protects from spiritual vulnerability."},
{topic:"Discipline",ref:"1 Peter 4:7",text:"Be self-controlled and alert.",exp:"Spiritual alertness requires discipline."},
{topic:"Discipline",ref:"Psalm 94:12",text:"Blessed is the one You discipline, Lord.",exp:"Discipline leads to blessing and growth."},
{topic:"Discipline",ref:"Proverbs 3:11-12",text:"Do not despise the Lord’s discipline.",exp:"God’s guidance is beneficial when accepted humbly."},

/* HOPE */
{topic:"Hope",ref:"Romans 15:13",text:"May the God of hope fill you with all joy and peace as you trust in Him.",exp:"Hope produces joy and peace in believers."},
{topic:"Hope",ref:"Jeremiah 29:11",text:"I know the plans I have for you... plans to give you a hope and a future.",exp:"God’s plans assure believers of a hopeful future."},
{topic:"Hope",ref:"Psalm 39:7",text:"My hope is in You.",exp:"Trust in God is the foundation of hope."},
{topic:"Hope",ref:"Lamentations 3:21-23",text:"This I call to mind and therefore I have hope.",exp:"Remembering God’s faithfulness sustains hope."},
{topic:"Hope",ref:"Romans 5:5",text:"God’s love has been poured into our hearts through the Holy Spirit.",exp:"Hope is strengthened by God’s love within us."},
{topic:"Hope",ref:"Hebrews 6:19",text:"We have this hope as an anchor for the soul.",exp:"Hope provides stability in uncertainty."},
{topic:"Hope",ref:"1 Peter 1:3",text:"He has given us new birth into a living hope through the resurrection of Jesus Christ.",exp:"Faith in Christ produces enduring hope."},
{topic:"Hope",ref:"Psalm 71:5",text:"For You are my hope, O Lord God.",exp:"God Himself is the ultimate source of hope."},
{topic:"Hope",ref:"Romans 8:24-25",text:"Hope that is seen is no hope at all.",exp:"Hope requires patient waiting and trust in God’s promises."},
{topic:"Hope",ref:"Isaiah 40:31",text:"Those who hope in the Lord will renew their strength.",exp:"Hope revitalizes perseverance and courage."},

/* JOY IN TRIALS */
{topic:"Joy in Trials",ref:"James 1:2-3",text:"Consider it pure joy whenever you face trials, because the testing of your faith produces perseverance.",exp:"Trials refine character and strengthen faith, leading to lasting joy."},
{topic:"Joy in Trials",ref:"1 Peter 1:6-7",text:"Though you have not seen Him, you love Him; the trials refine faith.",exp:"Faith tested through trials matures into deeper spiritual understanding."},
{topic:"Joy in Trials",ref:"Romans 5:3-4",text:"We rejoice in our sufferings, knowing that suffering produces perseverance.",exp:"Endurance through difficulties fosters hope and maturity."},
{topic:"Joy in Trials",ref:"2 Corinthians 4:17",text:"Our light and momentary troubles achieve for us an eternal glory.",exp:"Temporary hardships lead to eternal reward."},
{topic:"Joy in Trials",ref:"Philippians 1:29",text:"You have been granted not only to believe in Christ but also to suffer for Him.",exp:"Suffering for Christ is a privilege producing joy."},
{topic:"Joy in Trials",ref:"1 Thessalonians 5:16-18",text:"Rejoice always, pray continually, give thanks in all circumstances.",exp:"Joy is sustained through gratitude and prayer."},
{topic:"Joy in Trials",ref:"Romans 8:28",text:"In all things God works for the good of those who love Him.",exp:"Even trials contribute to God’s purpose."},
{topic:"Joy in Trials",ref:"Psalm 30:5",text:"Weeping may stay for the night, but rejoicing comes in the morning.",exp:"Joy follows periods of hardship."},
{topic:"Joy in Trials",ref:"Habakkuk 3:18",text:"I will rejoice in the Lord, I will be joyful in God my Savior.",exp:"Inner joy is independent of external circumstances."},
{topic:"Joy in Trials",ref:"Nehemiah 8:10",text:"The joy of the Lord is your strength.",exp:"Joy provides endurance and power during trials."}/* ===== TOPICS 91–100 ===== */

/* PERSEVERANCE */
{topic:"Perseverance",ref:"Galatians 6:9",text:"Let us not become weary in doing good, for at the proper time we will reap a harvest if we do not give up.",exp:"Perseverance ensures eventual reward through faithfulness."},
{topic:"Perseverance",ref:"James 1:12",text:"Blessed is the one who perseveres under trial.",exp:"Endurance under testing produces blessing."},
{topic:"Perseverance",ref:"Romans 5:3-4",text:"Suffering produces perseverance; perseverance, character; character, hope.",exp:"Trials refine character and deepen hope."},
{topic:"Perseverance",ref:"2 Thessalonians 3:13",text:"Do not grow weary in doing good.",exp:"Consistent effort in righteousness is encouraged."},
{topic:"Perseverance",ref:"Hebrews 10:36",text:"You need to persevere so that when you have done the will of God, you will receive what He has promised.",exp:"Perseverance is tied to fulfilling God’s will and receiving His promises."},
{topic:"Perseverance",ref:"Colossians 1:11",text:"Being strengthened with all power according to His glorious might so that you may have great endurance.",exp:"God provides the power to persevere through difficulties."},
{topic:"Perseverance",ref:"Romans 8:25",text:"But if we hope for what we do not yet have, we wait for it patiently.",exp:"Perseverance combines hope with patient waiting."},
{topic:"Perseverance",ref:"James 5:11",text:"The Lord is full of compassion and mercy.",exp:"Patience and perseverance trust in God’s justice."},
{topic:"Perseverance",ref:"1 Corinthians 15:58",text:"Always give yourselves fully to the work of the Lord.",exp:"Faithful labor continues without discouragement."},
{topic:"Perseverance",ref:"Philippians 3:14",text:"Press on toward the goal to win the prize.",exp:"Perseverance focuses on eternal objectives."},

/* PRAYER */
{topic:"Prayer",ref:"1 Thessalonians 5:17",text:"Pray without ceasing.",exp:"Prayer is continual communication with God."},
{topic:"Prayer",ref:"Philippians 4:6",text:"Do not be anxious about anything, but in every situation, by prayer and petition, with thanksgiving, present your requests to God.",exp:"Prayer brings peace and releases anxiety."},
{topic:"Prayer",ref:"Matthew 6:6",text:"When you pray, go into your room, close the door and pray to your Father.",exp:"Private, sincere prayer deepens intimacy with God."},
{topic:"Prayer",ref:"James 5:16",text:"The prayer of a righteous person is powerful and effective.",exp:"Righteous living amplifies the effectiveness of prayer."},
{topic:"Prayer",ref:"Mark 11:24",text:"Whatever you ask for in prayer, believe that you have received it.",exp:"Faith is critical for answered prayer."},
{topic:"Prayer",ref:"Romans 12:12",text:"Be joyful in hope, patient in affliction, faithful in prayer.",exp:"Prayer is a stabilizing force in life."},
{topic:"Prayer",ref:"Colossians 4:2",text:"Devote yourselves to prayer, being watchful and thankful.",exp:"Persistent prayer with gratitude is essential."},
{topic:"Prayer",ref:"Luke 18:1",text:"Always pray and not give up.",exp:"Consistency in prayer nurtures spiritual perseverance."},
{topic:"Prayer",ref:"Psalm 145:18",text:"The Lord is near to all who call on Him.",exp:"Prayer connects believers with God’s presence."},
{topic:"Prayer",ref:"Jeremiah 29:12",text:"Then you will call on me and come and pray to me, and I will listen to you.",exp:"God hears and responds to heartfelt prayer."},

/* ETERNAL LIFE */
{topic:"Eternal Life",ref:"John 3:16",text:"For God so loved the world that He gave His one and only Son, that whoever believes in Him shall not perish but have eternal life.",exp:"Faith in Christ grants eternal life as a gift of God’s love."},
{topic:"Eternal Life",ref:"John 17:3",text:"Now this is eternal life: that they know You, the only true God, and Jesus Christ, whom You have sent.",exp:"Eternal life is relational—knowing God personally."},
{topic:"Eternal Life",ref:"Romans 6:23",text:"The gift of God is eternal life in Christ Jesus our Lord.",exp:"Salvation is a gift, not earned by works."},
{topic:"Eternal Life",ref:"1 John 5:11-12",text:"God has given us eternal life, and this life is in His Son.",exp:"Belief in Jesus grants participation in eternal life."},
{topic:"Eternal Life",ref:"Titus 1:2",text:"Hope of eternal life, which God, who does not lie, promised before the beginning of time.",exp:"Eternal life is guaranteed by God’s promise."},
{topic:"Eternal Life",ref:"John 5:24",text:"Whoever hears my word and believes Him who sent me has eternal life.",exp:"Faith in Christ secures eternal life now and forever."},
{topic:"Eternal Life",ref:"1 Peter 1:3-4",text:"We have a new birth into a living hope through the resurrection of Jesus Christ.",exp:"Eternal life begins as a present hope and future reality."},
{topic:"Eternal Life",ref:"Romans 8:38-39",text:"Nothing can separate us from the love of God in Christ Jesus.",exp:"Eternal life is secure in God’s unwavering love."},
{topic:"Eternal Life",ref:"John 6:47",text:"Very truly I tell you, the one who believes has eternal life.",exp:"Belief in Jesus ensures eternal life immediately."},
{topic:"Eternal Life",ref:"2 Timothy 1:10",text:"He has brought life and immortality to light through the gospel.",exp:"The gospel reveals the path to eternal life."}];
